#+TITLE: Project Diary for "Cosmological parameter estimation using Bayesian accelerated Machine learning"
#+AUTHOR: Aleksandr Petrosyan
#+BIBLIOGRAPHY: bibliography
* Michaelmas Term

  Doing some research about the subject. 

  
** Terminology

   Prior - \(P(\theta | M)\)
   Likelihood - \(P(M, \theta | Data)\)
   
   Posterior - \(P(\theta | Data)\)
   Evidence - \(P(Model | Data)\)

   Bayes' theorem says that 

   \[Likelihood \times Prior = Posterior \times Evidence\]

   So can use this to find the parameter values of a model, + the likelihood that the model fits the data at all. 

   
** How does nested sampling work

*** Skilling's paper

	\cite{skilling2006}
	
	Nested Sampling is a machine learning technique that allows to do Bayesian parameter estimation. 

	Fitting a line to data is an example of a parameter fitting model. 

	Set \( 
	\chi^{2} \triangleq \sum_{i} \left(\frac{y_{i} - f(x_{i}, \theta)}{\sigma_{i}} \right)
	\). We need to ask a question, how likely is the data observed, given that the model is true, and the Model parameters have the given values. The probability is usually given by a Gaussian (or normal distribution). 
	
	\[ 
	L = \frac{1}{N} \exp{\left[ - \chi^{2}\right]}
	\]
	
	
	
